### PR TITLE
Add/Remove track to favorites. Load permission after login

### PR DESCRIPTION
**Pull request by filipkristo**

### CODE REVIEW

**Comment by projectgoav** [comment]
Looks good to me. A couple of things I might suggest, but feel free to let me know if you don't think they shouldn't be done!

- Add a favourite method to the ITrack interface, so you can favourite directly from a track as well as a User
- I think the favourite method from Deezer supports multiple Ids at once. If it does, it might be nice to have this as an option

**Comment by filipkristo** [comment]
I think favorite methods supports only one track id, based on deezer documentation. 

image

**Comment by filipkristo** [comment]
Based on api documentation I also changed track it from long to int. Is that OK?

**Comment by projectgoav** [comment]
Looks fine to me! Just a note, that you don't need to increment the version :)

**Pull request merged**
